name: Demo

on:
  workflow_dispatch:

jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      # Add your job steps here
      - name: Run My demo here
        run: |
          echo "This job runs on push without a specific branch."
