# Github runner for eslint instance should be working now in github as well
name: ESLint

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true
